apiVersion: v2
appVersion: "0.1"
description: A Helm chart tissuumaps apps
name: tissuumaps
version: 1.0.7
maintainers:
  - name: Team Whale
    email: serve@scilifelab.se
dependencies:
  - name: common
    version: "0.1.0"
    repository: "file://../common"
