appname: shinyapp
name: shinyapp
project:
  name: project
  slug: project-slug

appconfig:
  proxyimage: ghcr.io/scilifelabdatacentre/serve-shinyproxy:240703-0833
  proxyport: 8080
  port: 3838
  image:
  path: /home
  minimumSeatsAvailable: 1
  seatsPerContainer: 1
  allowContainerReuse: false
  site_dir: /srv/shiny-server


global:
  domain: localhost

apps:
  volumeK8s:

service:
  name: shinyproxy-svc

ingress:
  secretName: prod-ingress
  clientMaxBodySize: 2000M

s3sync:
  image: scaleoutsystems/s3-sync:latest

podSecurityContext:
  seccompProfile:
    type: RuntimeDefault
  fsGroup: 1000

securityContext:
  runAsNonRoot: true
  runAsUser: 1000
  runAsGroup: 1000
  allowPrivilegeEscalation: false
  privileged: false
  capabilities:
    drop:
      - all

flavor:
  limits:
    cpu: 1
    ephemeral-storage: 800Mi
    memory: 1Gi
  requests:
    cpu: 500m
    ephemeral-storage: 500Mi
    memory: 500Mi
