apiVersion: v2
appVersion: "0.1"
description: A Helm chart for Jupyter Lab
name: lab
version: 1.0.10
maintainers:
  - name: Team Whale
    email: serve@scilifelab.se
dependencies:
  - name: common
    version: "0.1.1"
    repository: "file://../common"
