appname: jupyter-lab
project:
  name: project
  slug: project-slug

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: nvidia.com/gpu.present
          operator: In
          values:
          - "true"

global:
  domain: localhost

apps:
  volumek8s:

minio:
  access_key: minio
  secret_key: minio123
  bucket: dataset

appconfig:
  port: 8888
  image: ghcr.io/scilifelabdatacentre/serve-jupyterlab:231030-1145

service:
  name: jupyterlab-svc
  port: 80

ingress:
  v1beta1: false
  secretName: prod-ingress

mlflow:
  url: ""
  s3url: ""
  access_key: ""
  secret_key: ""
  region: ""
  username: ""
  password: ""

podSecurityContext:
  seccompProfile:
    type: RuntimeDefault
  fsGroup: 100

securityContext:
  runAsNonRoot: true
  runAsUser: 1000
  runAsGroup: 100
  allowPrivilegeEscalation: false
  privileged: false
  capabilities:
    drop:
      - all

flavor:
  limits:
    cpu: 1
    ephemeral-storage: 800Mi
    memory: 1Gi
  requests:
    cpu: 500m
    ephemeral-storage: 500Mi
    memory: 500Mi
