namespace: default
appname: filemanager
project:
  name: project
  slug: project-slug

permission: public

global:
  protocol: TCP'
  domain: studio.127.0.0.1.nip.io
  auth_domain: studio.127.0.0.1.nip.io

ingress:
  v1beta1: false
  secretName: prod-ingress

apps:
  volumeK8s: {}

appconfig:
  image: ghcr.io/scilifelabdatacentre/serve-filemanager:240221-0930

service:
  name: filemanager-svc
  port: 8080
  targetPort: 8080

podSecurityContext:
  seccompProfile:
    type: RuntimeDefault
  fsGroup: 1000

securityContext:
  runAsNonRoot: true
  runAsUser: 1000
  runAsGroup: 1000
  allowPrivilegeEscalation: false
  privileged: false
  capabilities:
    drop:
      - all
