apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
  - {{ .Values.volume.accessModes }}
  {{ if .Values.volume.storageClass }}
  storageClassName: {{ .Values.volume.storageClass }}
  {{ end }}
  resources:
    requests:
      storage: {{ .Values.volume.size }}
status: {}
