apiVersion: v1
appVersion: "1.1.0-beta"
description: A Helm chart for deploying Serve
name: studio
version: 1.0.0
maintainers:
  - email: serve@scilifelab.se
    name: Team Whale

dependencies:
  - name: reloader
    version: v1.0.15
    repository: https://stakater.github.io/stakater-charts
    condition: reloader.enabled

  - name: postgresql
    version: 12.2.7
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  
  - name: redis
    version: 17.7.4
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
  
  - name: rabbitmq
    version: 11.16.2
    repository: https://charts.bitnami.com/bitnami
    condition: rabbitmq.enabled

  - name: common
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-common
    version: 2.0.4
