name: New Helm chart version for Shiny

on:
  pull_request:
    paths:
      - "apps/shiny/Chart.yaml"

jobs:
  update-json:
    runs-on: ubuntu-latest
    steps:
      - name: Check out serve-charts repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.TW_PAT }}

      - name: Set up environment variables
        run: |
          HELM_CHART=shinyapp
          echo "HELM_CHART=$HELM_CHART" >> "$GITHUB_ENV"
          NEW_CHART_VERSION=$(yq e '.version' apps/shiny/Chart.yaml)
          echo "NEW_CHART_VERSION=$NEW_CHART_VERSION" >> $GITHUB_ENV
          echo "JSON_FILE_PATH=fixtures/apps_fixtures.json" >> $GITHUB_ENV

      - name: Set up the SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.TW_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Clone the Serve repository
        run: |
          git config --global user.name "$GITHUB_ACTOR"
          git config --global user.email "teamwhale@scilifelab.se"
          git clone git@github.com:ScilifelabDataCentre/serve.git

      - name: Import GPG key and configure commit signing
        run: |
          echo "${{ secrets.TW_GPG_PRIVATE_KEY }}" | gpg --batch --import
          git config --global user.signingkey "${{ secrets.GPG_KEY_ID }}"
          git config --global commit.gpgsign true
        env:
          GPG_PRIVATE_KEY: ${{ secrets.TW_GPG_PRIVATE_KEY }}

      - name: Update JSON file in the Serve repository
        run: |
          cd serve
          jq -M --arg new_chart_version "$NEW_CHART_VERSION" 'map(if .fields.chart | contains("${{ env.HELM_CHART }}:") then .fields.chart |= sub(":[^:]+$"; ":" + $new_chart_version) else . end)' $JSON_FILE_PATH > tmp.json
          mv tmp.json $JSON_FILE_PATH
          git add $JSON_FILE_PATH
          git diff --quiet || git commit -S -m "Update chart version in ${{ env.HELM_CHART }} to ${{ env.NEW_CHART_VERSION }}"

      - name: Push changes to the Serve repository
        run: |
          cd serve
          git push origin HEAD
        env:
          GITHUB_TOKEN: ${{ secrets.TW_PAT }}

      - name: Create a pull request in the Serve repository
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.TW_PAT }}
          commit-message: "Update apps_fixtures.json"
          committer: ${{ github.actor }} <teamwhale@scilifelab.se>
          author: ${{ github.actor }} <teamwhale@scilifelab.se>
          branch: update/${{ env.HELM_CHART }}-${{ env.NEW_CHART_VERSION }}
          title: 'Update chart version in ${{ env.HELM_CHART }} to ${{ env.NEW_CHART_VERSION }}'
          body: |
            This PR updates the `chart` field in `app_fixtures.json` to use the new version: `${{ env.NEW_CHART_VERSION }}`.
            Please review and merge if everything looks good.
          path: serve
