apiVersion: batch/v1
kind: Job
metadata:
  name: "delete-user-pods-{{ .Release.Name }}"
  labels:
    {{- include "shinyproxy.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-delete
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  backoffLimit: {{ .Values.hooks.deleteUserPods.backoffLimit }}
  activeDeadlineSeconds: {{ .Values.hooks.deleteUserPods.activeDeadlineSeconds }}
  template:
    metadata:
      name: "delete-user-pods-{{ .Release.Name }}"
      labels:
        {{- include "shinyproxy.labels" . | nindent 8 }}
        allow-api-access: "true"
    spec:
      restartPolicy: Never
      serviceAccountName: {{ .Release.Namespace }}-shinyproxy
      containers:
      - name: delete-user-pods
        image: {{ .Values.hooks.deleteUserPods.image }}
        args:
          - "delete"
          - "pods"
          - "-l"
          - "sp.instance={{ .Release.Name }}"
          - "-n"
          - "{{ .Release.Namespace }}"
