{{- if (include "stackn.createSecret" .) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "common.names.fullname" . }}
  labels:
  {{- include "common.labels.standard" . | nindent 4 }}
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  studio-superuser-password: {{ include "common.secrets.passwords.manage" (dict "secret" (include "common.names.fullname" .) "key" "studio-superuser-password" "providedValues" (list "global.studio.superuserPassword" "studio.superuserPassword") "context" $) }}
  event-user-password: {{ include "common.secrets.passwords.manage" (dict "secret" (include "common.names.fullname" .) "key" "event-user-password" "providedValues" (list "global.studio.eventuserPassword" "studio.eventuserPassword") "context" $) }}
  rabbit-password:  {{ include "common.secrets.passwords.manage" (dict "secret" (include "common.names.fullname" .) "key" "rabbit-password" "providedValues" (list "rabbit.password") "context" $) }}
  django-secret-key:  {{ include "common.secrets.passwords.manage" (dict "secret" (include "common.names.fullname" .) "key" "django-secret-key" "providedValues" (list "studio.djangoSecret") "length" 50 "strong" true "context" $) }}
  {{ if .Values.studio.emailService.enabled }}
  email-google-service-account-type: {{ .Values.studio.emailService.googleServiceAccount.type }}
  email-google-service-account-project_id: {{ .Values.studio.emailService.googleServiceAccount.project_id }}
  email-google-service-account-private_key_id: {{ .Values.studio.emailService.googleServiceAccount.private_key_id }}
  email-google-service-account-private_key: {{ .Values.studio.emailService.googleServiceAccount.private_key | b64enc }}
  email-google-service-account-client_email: {{ .Values.studio.emailService.googleServiceAccount.client_email }}
  email-google-service-account-client_id: {{ .Values.studio.emailService.googleServiceAccount.client_id }}
  email-google-service-account-auth_uri: {{ .Values.studio.emailService.googleServiceAccount.auth_uri }}
  email-google-service-account-token_uri: {{ .Values.studio.emailService.googleServiceAccount.token_uri }}
  email-google-service-account-auth_provider_x509_cert_url: {{ .Values.studio.emailService.googleServiceAccount.auth_provider_x509_cert_url }}
  email-google-service-account-client_x509_cert_url: {{ .Values.studio.emailService.googleServiceAccount.client_x509_cert_url }}
  email-google-service-account-universe_domain: {{ .Values.studio.emailService.googleServiceAccount.universe_domain }}
  {{ end }}
  {{ if .Values.studio.githubApiToken }}
  github-api-token: {{ .Values.studio.githubApiToken | b64enc }}
  {{ end }}
{{- end -}}
