{{- if (include "studio.createSecret" .) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "common.names.fullname" . }}
  labels:
  {{- include "common.labels.standard" . | nindent 4 }}
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  studio-superuser-password: {{ include "common.secrets.passwords.manage" (dict "secret" (include "common.names.fullname" .) "key" "studio-superuser-password" "providedValues" (list "studio.superuserPassword" "studio.superuserPassword") "context" $) }}
  event-user-password: {{ include "common.secrets.passwords.manage" (dict "secret" (include "common.names.fullname" .) "key" "event-user-password" "providedValues" (list "studio.eventuserPassword" "studio.eventuserPassword") "context" $) }}
  rabbitmq-password:  {{ include "common.secrets.passwords.manage" (dict "secret" (include "common.names.fullname" .) "key" "rabbitmq-password" "providedValues" (list "rabbitmq.password") "context" $) }}
  django-secret-key:  {{ include "common.secrets.passwords.manage" (dict "secret" (include "common.names.fullname" .) "key" "django-secret-key" "providedValues" (list "studio.djangoSecret") "length" 50 "strong" true "context" $) }}
  altcha-hmac-key: {{ include "common.secrets.passwords.manage" (dict "secret" (include "common.names.fullname" .) "key" "altcha-hmac-key" "providedValues" (list "studio.altchaHmacKey") "length" 50 "strong" true "context" $) }}
  {{ if .Values.studio.emailService.enabled }}
  email-google-service-account-type: {{ .Values.studio.emailService.googleServiceAccount.type | b64enc }}
  email-google-service-account-project-id: {{ .Values.studio.emailService.googleServiceAccount.project_id | b64enc }}
  email-google-service-account-private-key-id: {{ .Values.studio.emailService.googleServiceAccount.private_key_id | b64enc }}
  email-google-service-account-private-key: {{ .Values.studio.emailService.googleServiceAccount.private_key | b64enc }}
  email-google-service-account-client-email: {{ .Values.studio.emailService.googleServiceAccount.client_email | b64enc }}
  email-google-service-account-client-id: {{ .Values.studio.emailService.googleServiceAccount.client_id | b64enc }}
  email-google-service-account-auth-uri: {{ .Values.studio.emailService.googleServiceAccount.auth_uri | b64enc }}
  email-google-service-account-token-uri: {{ .Values.studio.emailService.googleServiceAccount.token_uri | b64enc }}
  email-google-service-account-auth-provider-x509-cert-url: {{ .Values.studio.emailService.googleServiceAccount.auth_provider_x509_cert_url | b64enc }}
  email-google-service-account-client-x509-cert-url: {{ .Values.studio.emailService.googleServiceAccount.client_x509_cert_url | b64enc }}
  email-google-service-account-universe-domain: {{ .Values.studio.emailService.googleServiceAccount.universe_domain | b64enc }}
  {{ end }}
  {{ if .Values.studio.githubApiToken }}
  github-api-token: {{ .Values.studio.githubApiToken | b64enc }}
  {{ end }}
  {{ if .Values.studio.dockerhubToken }}
  docker-hub-token: {{ .Values.studio.dockerhubToken | b64enc }}
  {{ end }}
{{- end -}}
