# Configuration for the default backend: service and handling of a 404 error on a subdomain level (wild card domain).
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-errors
  labels:
    app.kubernetes.io/name: nginx-errors
    app.kubernetes.io/part-of: ingress-nginx
spec:
  selector:
    app.kubernetes.io/name: nginx-errors
    app.kubernetes.io/part-of: ingress-nginx
  ports:
  - port: 80
    targetPort: 8080
    name: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-errors
  labels:
    app.kubernetes.io/name: nginx-errors
    app.kubernetes.io/part-of: ingress-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: nginx-errors
      app.kubernetes.io/part-of: ingress-nginx
  template:
    metadata:
      labels:
        app.kubernetes.io/name: nginx-errors
        app.kubernetes.io/part-of: ingress-nginx
    spec:
      containers:
      - name: nginx-error-server
        image: registry.k8s.io/ingress-nginx/custom-error-pages:v1.0.2@sha256:b2259cf6bfda813548a64bded551b1854cb600c4f095738b49b4c5cdf8ab9d21
        ports:
        - containerPort: 8080
        # Mounting custom error page from ConfigMap 1
        volumeMounts:
        - name: custom-error-pages-404
          mountPath: /www/404.html
          subPath: 404.html
        # Mounting custom error page from ConfigMap 2
        - name: custom-error-pages-503
          mountPath: /www/503.html
          subPath: 503.html

      # Mounting volumes from two ConfigMaps
      volumes:
      - name: custom-error-pages-404
        configMap:
          name: custom-error-pages-404
          items:
          - key: "404"
            path: "404.html"
      - name: custom-error-pages-503
        configMap:
          name: custom-error-pages-503
          items:
          - key: "503"
            path: "503.html"
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/custom-http-errors: 503,404
    nginx.ingress.kubernetes.io/default-backend: nginx-errors
  name: wildcard-test-srv-dev
  namespace: serve-dev
spec:
  defaultBackend:
    service:
      name: nginx-errors
      port:
        number: 80
  rules:
  - host: '*.{{ .Values.domain }}'
    http:
      paths:
      - backend:
          service:
            name: nginx-errors
            port:
              number: 80
        path: /404.html
        pathType: ImplementationSpecific
  tls:
  - hosts:
    - '*.serve-dev.scilifelab.se'
    secretName: prod-ingress

