{{- if and .Values.gateway.enabled .Values.gateway.rateLimit.enabled }}
apiVersion: gateway.nginx.org/v1alpha1
kind: RateLimitPolicy
metadata:
  name: {{ .Release.Name }}-rate-limit
spec:
  targetRefs:
  - group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: {{ .Release.Name }}-httproute
  rateLimit:
    dryRun: {{ .Values.gateway.rateLimit.dryRun | default false }}
    local:
      rules:
      - key: $binary_remote_addr
        rate: {{ .Values.gateway.rateLimit.rate | default "6r/s" }}
        burst: {{ .Values.gateway.rateLimit.burst | default 20 }}
        noDelay: {{ .Values.gateway.rateLimit.noDelay | default true }}
        zoneSize: {{ .Values.gateway.rateLimit.zoneSize | default "10m" }}
{{- end }}
