apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    reloader.stakater.com/auto: "true"
  labels:
    io.kompose.service: {{ .Release.Name }}-studio
    name: {{ .Release.Name }}-studio
  name: {{ .Release.Name }}-studio
spec:
  replicas: {{ .Values.studio.replicas }}
  strategy:
    type: {{ .Values.studio.strategy.type }}
  selector:
    matchLabels:
      name: {{ .Release.Name }}-studio
  template:
    metadata:
      {{- if .Values.studio.metrics.enabled }}
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: /metrics
        prometheus.io/port: "8080"
      {{- end }}
      labels:
        io.kompose.service: {{ .Release.Name }}-studio
        name: {{ .Release.Name }}-studio
        web: studio-web
        app: studio-app
        allow-api-access: "true"
        networking/allow-internet-egress: "true"
    spec:
      automountServiceAccountToken: true
      serviceAccountName: {{ include "common.names.fullname" .}}
      securityContext:
        fsGroup: {{ .Values.studio.securityContext.fsGroup }}
      initContainers:
        {{ if and .Values.studio.debug .Values.studio.media.storage.mountStudio }}
        - name: volume-permissions
          image: busybox
          command: ['sh', '-c', 'chown -R 1000 {{ .Values.studio.media.mount_path }} && chgrp -R 1000 {{ .Values.studio.media.mount_path }}']
          volumeMounts:
          - name: mediavol
            mountPath: {{ .Values.studio.media.mount_path }}
          securityContext:
            runAsUser: 0
            runAsGroup: 0
            runAsNonRoot: false
        {{ end }}
        - name: wait-for-db
          image: postgres
          command: ['sh', '-c', 'until pg_isready --host={{ .Values.postgresql.fullnameOverride }} --port={{ .Values.postgresql.primary.service.ports.postgresql }}; do echo waiting for database; sleep 2; done;']
          resources:
            limits:
              cpu: "100m"
              memory: "512Mi"
            requests:
              cpu: "100m"
              memory: "512Mi"
        {{- if .Values.studio.initContainer.enabled }}
        - name: studio-init
          image: {{ .Values.studio.image.repository }}:{{ .Values.studio.image.tag }}
          imagePullPolicy: {{ .Values.studio.image.pullPolicy }}
          env:
          - name: INIT
            value: {{ .Values.studio.init | quote }}
          - name: RESET_DB
            value: {{ .Values.studio.reset_db | quote }}
          - name: STUDIO_STORAGECLASS
            value: {{ include "studio.storageclass" . }}
          - name: STUDIO_ACCESSMODE
            value: {{ .Values.access_mode }}
          {{- include "studio.env" . | nindent 10 }}
          command: ['sh', 'scripts/init_run_web.sh']
          volumeMounts:
            {{- if .Values.chartcontroller.addSecret }}
            - name: kubeconfig
              mountPath: {{ .Values.studio.kubeconfig_dir | quote }}
              readOnly: true
            {{- end }}
            - mountPath: /app/studio/settings.py
              subPath: settings.py
              name: {{ .Release.Name}}-settings-configmap
            {{ if .Values.studio.media.storage.mountStudio }}
            - name: mediavol
              mountPath: {{ .Values.studio.media.mount_path }}
            {{ end }}
            {{ if eq .Values.environment "local" }}
            - mountPath: /app
              name: sourcecode
            {{ end }}
          resources:
            limits:
              cpu: {{ .Values.studio.resources.limits.cpu }}
              memory: {{ .Values.studio.resources.limits.memory }}
            requests:
              cpu: {{ .Values.studio.resources.requests.cpu }}
              memory: {{ .Values.studio.resources.requests.memory }}
        {{- end }}
      containers:
      - args:
        - sh
        {{ if eq .Values.environment "local" }}
        - -c
        - "/usr/sbin/sshd -D"
        {{ else }}
        - scripts/run_web.sh
        {{ end }}
        ports:
        - containerPort: 8080
        {{- if eq .Values.environment "local" }}
        - containerPort: 22
        {{- end }}
        env:
        - name: INIT
          value: {{ .Values.studio.init | quote }}
        - name: RESET_DB
          value: {{ .Values.studio.reset_db | quote }}
        - name: STUDIO_STORAGECLASS
          value: {{ include "studio.storageclass" . }}
        - name: STUDIO_ACCESSMODE
          value: {{ .Values.access_mode }}
        {{- include "studio.env" . | nindent 8 }}
        image: {{ .Values.studio.image.repository }}:{{ .Values.studio.image.tag }}
        imagePullPolicy: {{ .Values.studio.image.pullPolicy }}
        name: {{ .Release.Name }}-studio
        volumeMounts:
          {{- if .Values.chartcontroller.addSecret }}
          - name: kubeconfig
            mountPath: {{ .Values.studio.kubeconfig_dir | quote }}
            readOnly: true
          {{- end }}
          - mountPath: /app/studio/settings.py
            subPath: settings.py
            name: {{ .Release.Name}}-settings-configmap
          {{ if .Values.studio.media.storage.mountStudio }}
          - name: mediavol
            mountPath: {{ .Values.studio.media.mount_path }}
          {{ end }}
          {{ if eq .Values.environment "local" }}
          - mountPath: /app
            name: sourcecode
          {{ end }}
        resources:
          limits:
            cpu: {{ .Values.studio.resources.limits.cpu }}
            memory: {{ .Values.studio.resources.limits.memory }}
          requests:
            cpu: {{ .Values.studio.resources.requests.cpu }}
            memory: {{ .Values.studio.resources.requests.memory }}
        {{- if .Values.studio.securityContext.enabled }}
        securityContext:
          runAsUser: {{ .Values.studio.securityContext.runAsUser }}
          runAsGroup: {{ .Values.studio.securityContext.runAsGroup }}
          allowPrivilegeEscalation: {{ .Values.studio.securityContext.allowPrivilegeEscalation }}
          privileged: {{ .Values.studio.securityContext.privileged }}
          capabilities:
            drop:
              - all
        {{- end }}
        {{- if .Values.studio.readinessProbe.enabled }}
        readinessProbe:
          httpGet:
            path: {{ .Values.studio.readinessProbe.httpGet.path }}
            port: {{ .Values.studio.readinessProbe.httpGet.port }}
            scheme: {{ .Values.studio.readinessProbe.httpGet.scheme }}
            httpHeaders:
            {{- if .Values.studio.readinessProbe.httpGet.httpHeaders }}
              {{- range $i, $h := .Values.studio.readinessProbe.httpGet.httpHeaders }}
              - name: {{ $h.name | quote }}
                value: {{ $h.value | quote }}
              {{- end }}
              {{- else }}
              - name: "host"
                value: {{ .Release.Name }}-studio.{{ .Values.namespace | default "default" }}.svc.{{ .Values.cluster_domain | default "cluster.local"}}
            {{ end }}

          initialDelaySeconds: {{ .Values.studio.readinessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.studio.readinessProbe.periodSeconds }}
          timeoutSeconds: {{ .Values.studio.readinessProbe.timeoutSeconds | default 3 }}
          failureThreshold: {{ .Values.studio.readinessProbe.failureThreshold | default 2 }}
        {{- end }}
        {{- if .Values.studio.livenessProbe.enabled }}
        livenessProbe:
          httpGet:
            path: {{ .Values.studio.livenessProbe.httpGet.path }}
            port: {{ .Values.studio.livenessProbe.httpGet.port }}
            scheme: {{ .Values.studio.livenessProbe.httpGet.scheme }}
            httpHeaders:
            {{- if .Values.studio.livenessProbe.httpGet.httpHeaders }}
              {{- range $i, $h := .Values.studio.livenessProbe.httpGet.httpHeaders }}
              - name: {{ $h.name | quote }}
                value: {{ $h.value | quote }}
              {{- end }}
              {{- else }}
              - name: "host"
                value: {{ .Release.Name }}-studio.{{ .Values.namespace | default "default" }}.svc.{{ .Values.cluster_domain | default "cluster.local"}}
            {{ end }}

          initialDelaySeconds: {{ .Values.studio.livenessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.studio.livenessProbe.periodSeconds }}
          timeoutSeconds: {{ .Values.studio.livenessProbe.timeoutSeconds | default 3 }}
          failureThreshold: {{ .Values.studio.livenessProbe.failureThreshold | default 10 }}
        {{- end }}

      restartPolicy: Always
      volumes:
      {{- if .Values.chartcontroller.addSecret }}
      - name: kubeconfig
        secret:
          secretName: {{ .Release.Name }}-chart-controller-secret
      {{- end }}
      - name: {{ .Release.Name}}-settings-configmap
        configMap:
          name: {{ .Release.Name}}-settings-configmap
          items:
          - key: settings.py
            path: settings.py
      {{ if .Values.studio.media.storage.mountStudio }}
      - name: mediavol
        persistentVolumeClaim:
          claimName: {{ .Release.Name }}-{{ .Values.studio.media.storage.claimName }}
      {{ end }}
      {{ if eq .Values.environment "local" }}
      - hostPath:
          path: {{ .Values.source_code_path }}
          type: Directory
        name: sourcecode
      {{ end }}
