apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.20.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: {{ .Release.Name }}-celery-worker
    name: {{ .Release.Name }}-celery-worker
  name: {{ .Release.Name }}-celery-worker
spec:
  replicas: 2
  strategy:
    type: Recreate
  selector:
    matchLabels:
      name: {{ .Release.Name }}-celery-worker
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.20.0 ()
      creationTimestamp: null
      labels:
        io.kompose.service: {{ .Release.Name }}-celery-worker
        name: {{ .Release.Name }}-celery-worker
    spec:
      containers:
      - args:
        - sh
        - ./scripts/run_worker.sh
        env:
        - name: GET_HOSTS_FROM
          value: dns
        image: {{ .Values.studio.image.repository }}
        imagePullPolicy: Always
        name: {{ .Release.Name }}-celery-worker
        resources:
          limits:
            cpu: "500m"
            memory: "2Gi"
          requests:
            cpu: "100m"
            memory: "256Mi"
        volumeMounts:
          - name: config
            mountPath: "/app/chartcontroller/config/"
            readOnly: true
          - mountPath: /app/studio/settings.py
            subPath: settings.py
            name: {{ .Release.Name}}-settings-configmap
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      restartPolicy: Always
      volumes:
      - name: config
        secret:
          secretName: {{ .Release.Name }}-chart-controller-secret
      - name: {{ .Release.Name}}-settings-configmap
        configMap:
          name: {{ .Release.Name}}-settings-configmap
          items:
          - key: settings.py
            path: settings.py

status: {}
