# https://github.com/coder/code-server
apiVersion: v2
appVersion: "0.1"
description: A Helm chart for VS code in the browser
name: vscode
version: 1.0.9
maintainers:
  - name: Team Whale
    email: serve@scilifelab.se
dependencies:
  - name: common
    version: "0.1.2"
    repository: "file://../common"
