namespace: default
appname: vscode
project:
  name: project
  slug: project-slug

global:
  protocol: TCP

apps:
  volumek8s:

appconfig:
  port: 8080
  image: codercom/code-server:latest

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: acceleration
          operator: In
          values:
          - gpu

service:
  name: vscode-svc

imagePullSecrets:
  - name: regcred

ingress:
  v1beta1: false
  secretName: prod-ingress

podSecurityContext:
  seccompProfile:
    type: RuntimeDefault
  fsGroup: 1000

securityContext:
  runAsNonRoot: true
  runAsUser: 1000
  runAsGroup: 1000
  allowPrivilegeEscalation: false
  privileged: false
  capabilities:
    drop:
      - all

flavor:
  limits:
    cpu: 1
    ephemeral-storage: 800Mi
    memory: 1Gi
    nvidia.com/gpu:
  requests:
    cpu: 500m
    ephemeral-storage: 500Mi
    memory: 500Mi
    nvidia.com/gpu:
