appname: vscode
project:
  name: project
  slug: project-slug

global:
  protocol: TCP

  domain: studio.127.0.0.1.nip.io
  auth_domain: studio.127.0.0.1.nip.io

apps:
  volumek8s:

appconfig:
  image: ghcr.io/scilifelabdatacentre/serve-vscode:250312-1210

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: acceleration
          operator: In
          values:
          - gpu

service:
  name: vscode-svc
  port: 80
  targetport: 8080

ingress:
  v1beta1: false
  secretName: prod-ingress
  clientMaxBodySize: 100M

podSecurityContext:
  seccompProfile:
    type: RuntimeDefault
  fsGroup: 1000

securityContext:
  runAsNonRoot: true
  runAsUser: 1000
  runAsGroup: 1000
  allowPrivilegeEscalation: false
  privileged: false
  capabilities:
    drop:
      - all

flavor:
  limits:
    cpu: 1
    ephemeral-storage: 800Mi
    memory: 1Gi
    nvidia.com/gpu:
  requests:
    cpu: 500m
    ephemeral-storage: 500Mi
    memory: 500Mi
    nvidia.com/gpu:
