{{- if .Values.gateway.enabled }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ .Release.Name }}-httproute
  namespace: {{ .Release.Namespace }}
spec:
  hostnames:
  - "{{ .Release.Name }}.{{ .Values.global.domain }}"
  parentRefs:
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: {{ .Values.gateway.name | default "default" }}
    namespace: {{ .Values.gateway.namespace | default "gateway" }}
    port: {{ .Values.gateway.port | default 443 }}
  rules:
  - backendRefs:
    - name: {{ .Values.service.name }}
      kind: Service
      port: {{ .Values.service.port }}
    matches:
    - path:
        type: PathPrefix
        value: /
    {{- if and (ne .Values.permission "public") (ne .Values.permission "link") }}
    filters:
    - type: ExtensionRef
      extensionRef:
        group: gateway.nginx.org
        kind: SnippetsFilter
        name: {{ .Release.Name }}-auth
    {{- end }}
{{- end }}
