appname: dashapp
project:
  name: project
  slug: project-slug

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: nvidia.com/gpu.present
          operator: In
          values:
          - "true"

permission: public

global:
  protocol: TCP
  domain: studio.127.0.0.1.nip.io
  auth_domain: studio.127.0.0.1.nip.io

appconfig:
  port: 8000
  image: ghcr.io/scilifelabdatacentre/example-dash:latest

service:
  name: dashapp-svc
  port: 80

ingress:
  secretName: prod-ingress
  clientMaxBodySize: 100M

podSecurityContext:
  seccompProfile:
    type: RuntimeDefault
  fsGroup: 1000

securityContext:
  runAsNonRoot: true
  runAsUser: 1000
  runAsGroup: 1000
  allowPrivilegeEscalation: false
  privileged: false
  capabilities:
    drop:
      - all

flavor:
  limits:
    cpu: 1
    ephemeral-storage: 800Mi
    memory: 1Gi
  requests:
    cpu: 100m
    ephemeral-storage: 500Mi
    memory: 500Mi
