namespace: default
appname: dashapp
project:
  name: project
  slug: project-slug

permission: public

global:
  protocol: TCP

appconfig:
  port: 8000
  image: 

service:
  name: dashapp-svc

imagePullSecrets:
  - name: regcred

ingress:
  secretName: prod-ingress

podSecurityContext:
  seccompProfile:
      type: RuntimeDefault
  fsGroup: 1000

securityContext:
  runAsNonRoot: true
  runAsUser: 1000
  runAsGroup: 1000
  allowPrivilegeEscalation: false
  privileged: false
  capabilities:
    drop:
      - all

flavor:
  limits:
    cpu: 1
    ephemeral-storage: 800Mi
    memory: 1Gi
  requests:
    cpu: 500m
    ephemeral-storage: 500Mi
    memory: 500Mi