appname: dashapp
project:
  name: project
  slug: project-slug

permission: public

global:
  protocol: TCP'
  domain: studio.127.0.0.1.nip.io
  auth_domain: studio.127.0.0.1.nip.io

appconfig:
  port: 8000
  image: ghcr.io/scilifelabdatacentre/example-dash:latest

service:
  name: dashapp-svc
  port: 80

imagePullSecrets:
  - name: regcred

ingress:
  secretName: prod-ingress

podSecurityContext:
  seccompProfile:
    type: RuntimeDefault
  fsGroup: 1000

securityContext:
  runAsNonRoot: true
  runAsUser: 1000
  runAsGroup: 1000
  allowPrivilegeEscalation: false
  privileged: false
  capabilities:
    drop:
      - all

flavor: {}
