{{- if and .Values.tracking.enabled .Values.tracking.httproute.enabled .Values.tracking.httproute.clientMaxBodySize }}
apiVersion: gateway.nginx.org/v1alpha1
kind: ClientSettingsPolicy
metadata:
  name: {{ template "mlflow.v0.tracking.fullname" . }}-client-settings
  namespace: {{ include "common.names.namespace" . | quote }}
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: {{ template "mlflow.v0.tracking.fullname" . }}
  body:
    maxSize: {{ .Values.tracking.httproute.clientMaxBodySize | lower | quote }}
{{- end }}
