name: New Helm chart version for RStudio

on:
  pull_request:
    paths:
      - "apps/rstudio/Chart.yaml"

jobs:
  update-json:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_PAT }}

      - name: Set environment variables
        run: |
          HELM_CHART=rstudio
          echo "HELM_CHART=$HELM_CHART" >> "$GITHUB_ENV"
          NEW_CHART_VERSION=$(yq e '.version' apps/rstudio/Chart.yaml)
          echo "NEW_CHART_VERSION=$NEW_CHART_VERSION" >> $GITHUB_ENV
          echo "JSON_FILE_PATH=fixtures/apps_fixtures.json" >> $GITHUB_ENV

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Clone the Serve repo
        run: |
          git config --global user.name "$GITHUB_ACTOR"
          git config --global user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git clone git@github.com:ScilifelabDataCentre/serve.git

      - name: Update JSON file in Serve
        run: |
          cd serve
          jq -M --arg new_chart_version "$NEW_CHART_VERSION" 'map(if .fields.chart | contains("${{ env.HELM_CHART }}:") then .fields.chart |= sub(":[^:]+$"; ":" + $new_chart_version) else . end)' $JSON_FILE_PATH > tmp.json
          mv tmp.json $JSON_FILE_PATH
          git add $JSON_FILE_PATH
          git diff --quiet || git commit -m "Update chart version in ${{ env.HELM_CHART }} to ${{ env.NEW_CHART_VERSION }}"
      
      - name: Push Changes
        run: |
          cd serve
          git push origin HEAD
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GH_PAT }}
          commit-message: "Update apps_fixtures.json"
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          branch: update/${{ env.HELM_CHART }}-${{ env.NEW_CHART_VERSION }}
          title: 'Update chart version in ${{ env.HELM_CHART }} to ${{ env.NEW_CHART_VERSION }}'
          body: |
            This PR updates the `chart` field in `app_fixtures.json` to use the new version: `${{ env.NEW_CHART_VERSION }}`.
            Please review and merge if everything looks good.
          path: serve
