apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    run: {{ .Values.appname }}-python-serve
spec:
  ports:
  - port: {{ .Values.service.port }}
    targetPort: {{ .Values.appconfig.port }}
    protocol: TCP
  selector:
    release: {{ .Release.Name }}
